### ISSUE TITLE
Deploy screen shows 0/0 if game configuration is not done or not done correctly when deploy is selected

### ISSUE THREAD

**Issue by Maldor** [CHollingworth/Lampray#105]
**Describe the bug**

Deploy screen shows 0/0 if game configuration is not done or not done correctly when deploy is selected. Does not have a "Go back" option or an alert showing that something is wrong

**Error message**

Screen:
0/0
Log:
[LAMP:WARNING:9] Unable to load LAMP CONFIG:Check_Updates_Startup
[LAMP:LOG:0] Queue 'Deployment Start': Starting
[LAMP:LOG:0] Tracker data saved to Lamp_Data/Config/lampTrack.mdf
[LAMP:LOG:0] Task Complete.
[LAMP:LOG:0] Queue 'Deployment Start': Success
[LAMP:WARNING:11] Game Configuration not set.
[LAMP:LOG:0] Task Complete.
[LAMP:LOG:0] Queue 'Deployment Start': Success

**To Reproduce**

0. If set, remove <installDirPath> and <appDataPath> from conf.mdf found in [LAMP]/Lamp_data/Config
1. Open Lamp
2. Set mods (if any, not required)
3. Click Deploy
4. Click start
Note: Screen shows 0/0 with no option to go back

**Expected behaviour**

Warning about game configuration not being complete

**Screenshots**

**System Info (please complete the following information):**
 - Linux Flavour: SteamOS in desktop mode
 - Lamp Version: 1.3.2

**Additional context**
Ran across this as a newbie with trying to get Baldurs Gate 3 modded on my steam deck.

**Comment by hw-claudio** [comment]
I found the same issue. Just configure the directories manually to avoid this bug (in the menu, configure game, enter the two directories for the game manually from the directory selector).

It would likely make sense to provide a default configuration out of the box with the default directories (~/.steam/steamapps/... etc).

**Comment by hw-claudio** [comment]
click on the top left of the window to open the menu:

![Screenshot from 2024-01-03 21-45-46](https://github.com/CHollingworth/Lampray/assets/3407278/00f2a1a1-cfe9-4459-9326-cc731d60146c)

**Comment by CHollingworth** [comment]
The FAQ and the new wiki should resolve questions that people have.
