### ISSUE TITLE
mods do not seem to work (5e spells not showing any new spells at wizard level up)

### ISSUE THREAD

**Issue by hw-claudio** [CHollingworth/Lampray#115]
**Describe the bug**

Built and ran Lampray from latest git master.

Configured to use the directories:

~/.steam/steam/steamapps/common/Baldurs Gate 3
~/.steam/steam/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3

$ ls -lrt ~/.steam/steam/steamapps/common/Baldurs\ Gate\ 3/
-rwxrwxr-x 1 claudio claudio  579 Jan  2 23:39 InstallScript.vdf
drwxrwxr-x 2 claudio claudio 4096 Jan  2 23:40 DotNetCore
drwxrwxr-x 3 claudio claudio 4096 Jan  2 23:40 Data
drwxrwxr-x 4 claudio claudio 4096 Jan  2 23:40 Launcher
drwxrwxr-x 3 claudio claudio 4096 Jan  3 14:22 bin

$ ls -lrt ~/.steam/steam/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian\ Studios/Baldur\'s\ Gate\ 3/
drwxrwxr-x 3 claudio claudio 4096 Jan  2 23:42 PlayerProfiles
drwxrwxr-x 2 claudio claudio 4096 Jan  2 23:43 Mods
-rw-rw-r-- 1 claudio claudio  402 Jan  3 10:47 vkDeviceConfig.lsx
-rw-rw-r-- 1 claudio claudio 2060 Jan  3 14:22 graphicSettings.lsx
drwxrwxr-x 6 claudio claudio 4096 Jan  3 14:23 LevelCache
-rw-rw-r-- 1 claudio claudio  900 Jan  3 14:23 analytics.lsx
drwxrwxr-x 2 claudio claudio 4096 Jan  3 14:30 Temp

Deployed and Enabled Mods:

```
Mod Fixer-141-1-0-1692715645.zip                            Select Type           Load Order 0
BG3SE-Updater-20231028.zip                                  Engine Injection  Load Order 1
5eSpells-125-1-1-38-1703360961.zip                          Select Type           Load Order 2
UnlockLevelCurve-377-2-0-0-18-1703429481.zip    Select Type           Load Order 3
UnlockLevelCurve_Patch_5eSpells-377-2-0-0-17-1702500884.zip  Select Type Load Order 4
RAW-1329-4-0-1-0-1701618432.zip                             Select Type           Load Order 5
```

**Error message**

No errors, just zero effects from the mods.
On level up, the Wizard does not have any of the new 5e spells to select from.

**To Reproduce**

Steps to reproduce the behaviour:
1. Download the above mods from NexusMods, extract and repackage the RAW-1329-4-0-1-0-1701618432.rar mod into a .zip file
2. git clone of the Lampray project (master)
3. run ./setup.sh and ./build.sh
4. cd build
5. ./Lampray
6. Configure the BG3 game directories manually to the default values by using the Folder selector UI.
7. Drag the .zip files into the UI
8. Deploy and Enable all of the Mods
9. Start a New Game
10. Get to level 2 (on the beach after crash landing)
11. New spells to select from do not include any 5e spells Mod spells

**Expected behaviour**

Expected to be able to select new level 1 spells from the 5e spells Mod (f.e. Absorb Elements).

**Screenshots**

**System Info (please complete the following information):**
 - Linux Flavour: Ubuntu (PopOS)
 - Window Manager: default PopOS AutoTiling
 - Lamp Version: commit ee1145d67f586947510651b2e8de32fc283305c0

**Additional context**

It is the first time I attempt to use mods, so it is possible the issue is somewhere else in the way I expect them to work, any help appreciated.

Thanks

**Comment by CHollingworth** [comment]
You have not selected types for each mod leaving them as select type for some of them please refer to the wiki, @internetisaiah is currently rebuilding it but i believe the types should be as follows:

5e spells - standard mod
UnlockLevelCurve - standard mod
As i dont know the content of RAW-1329-4-0-1-0-1701618432 i cant say.

Sadly we cant use divinity, the windows api for mods we cant accurately auto-detect types so you'll have to set them yourself.

**Comment by hw-claudio** [comment]
thanks! Maybe defaulting to Standard Mod could be a good idea? 
Maybe some simple zip content file check could detect the most commonly used ones in other categories? 

Same could be done with the Bg3 directories configuration, putting in there the default would be a good idea I think.

Thanks
