### ISSUE TITLE
"cc1plus: some warnings being treated as errors"

### ISSUE THREAD

**Issue by rykugur** [CHollingworth/Lampray#134]
**Describe the bug**

Trying to build on nixOS and getting numerous warnings in the logs, and eventual failure with error: "cc1plus: some warnings being treated as errors"

**Error message**

A lamp error message from the logs, or the one on screen.

"cc1plus: some warnings being treated as errors"

**To Reproduce**

Steps to reproduce the behaviour:
1. be on nixOS
2. try to build [this derivation](https://gist.github.com/rykugur/9acac708083c65dcbf042bd8415b453b)
3. see error

**Expected behaviour**

Lampray to build without failure.

**Screenshots**

N/A

**System Info (please complete the following information):**

![image](https://github.com/CHollingworth/Lampray/assets/2609898/137bad21-cf51-45af-822b-77dc557527b0)

 - Linux Flavour: nixOS unstable
 - Window Manager: hyprland
 - Lamp Version: latest

**Additional context**

I'm relatively new to nixOS. Lampray was working for me on endeavourOS (installed via the AUR), but I cannot for the life of me get it to build on nixOS. Somebody responded to another issue here (https://github.com/CHollingworth/Lampray/issues/117#issuecomment-1902668830) (hence the `cmakeFlags` I added to my derivation), but no joy.

**Comment by rykugur** [comment]
Here's my build log: https://gist.github.com/rykugur/5624d7defeca2624e5e4bc76e3361191

**Comment by rykugur** [comment]
For reference I also started a discussion in the nixOS forums [here](https://discourse.nixos.org/t/trying-to-build-a-c-app-failing-due-to-warnings-being-treated-as-errors/40014)

**Comment by SnazzyPanda** [comment]
It looks like you are using the commit 79bac4cd307b579b516de7c99ec386b7b425cd46, which had a build error in it. Could you try using a newer commit, ideally the latest one (4673fef332976b991368aaeb62b968f531ab71ad) and see if that helps with the build at all?

**Comment by rykugur** [comment]
> It looks like you are using the commit [79bac4c](https://github.com/CHollingworth/Lampray/commit/79bac4cd307b579b516de7c99ec386b7b425cd46), which had a build error in it. Could you try using a newer commit, ideally the latest one ([4673fef](https://github.com/CHollingworth/Lampray/commit/4673fef332976b991368aaeb62b968f531ab71ad)) and see if that helps with the build at all?

Good call... I was originally on the latest version, but that was when I first tried building this... I should have checked before making this post. :facepalm:

That got me further (at least no errors yet); probably need to tinker a bit more, but it's a definite improvement. Thanks!

**Comment by rykugur** [comment]
Sorry to close/reopen. I was getting a weird error, but was able to figure it out. For posterity, it was:
```
./result/bin/Lampray: error while loading shared libraries: liblz4.so.1: cannot open shared object file: No such file or directory
```

I didn't see `lz4` in the docs as a requirement, but adding `lz4` to my `buildInputs` seems to have resolved the issue and I'm able to launch the app. Now just need to figure out the 7zip path (shouldn't be too hard) and hopefully good to go. Thanks again.

**Comment by Serpentian** [comment]
> I then ran into the p7zip couldn't be found issue. I was able to get around it temporarily by editing the conf.mdf file and hard-coding the path, but that "isn't really the nix way" and likely wouldn't work if I were try to import this into my nix config. I'll dig around and see if I can find a more permanent (declarative) solution.

@rykugur did you find the solution for that? And what is `conf.mdf` file?)

**Comment by rykugur** [comment]
> > I then ran into the p7zip couldn't be found issue. I was able to get around it temporarily by editing the conf.mdf file and hard-coding the path, but that "isn't really the nix way" and likely wouldn't work if I were try to import this into my nix config. I'll dig around and see if I can find a more permanent (declarative) solution.
> 
> @rykugur did you find the solution for that?

I eventually got it working in nixOS - [here's my derivation](https://github.com/rykugur/dotfiles/blob/master/pkgs/lampray/default.nix). Hope that helps.
