### ISSUE TITLE
X Error of failed request:  BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by hardbrocklife** [CHollingworth/Lampray#139]
Followed the install directions, Step 1 and Step 2. Ran the setup script then the build script without error. 

I also built it manually following Step. 

In both scenarios I get this output:

**Error**
> Lampray/build/Lampray 

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  175
  Current serial number in output stream:  176

If it threw an error for a dependency or something I would be able to independently research that issue and resolve it. I am not a developer, and have never ran into an output like this when compiling and running an application before.

**System Info**
OS: Manjaro Linux x86_64 
Kernel: 6.6.16-2-MANJARO 
Shell: bash 5.2.26 
DE: Plasma 5.27.11 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz 
GPU: NVIDIA GeForce RTX 3080 12GB 
Memory: 9933MiB / 64210MiB 

Any help would be appreciated. Excited about this application, but at a loss as to what to do next.

**Comment by SnazzyPanda** [comment]
I am not quite sure what might have happened with that compile error. If you are just looking to use Lampray, I would recommend grabbing the latest [release](https://github.com/CHollingworth/Lampray/releases). Since you are on Manjaro, you could also try the [AUR](http://aur.archlinux.org/packages/lampray), but I have no clue who maintains that, or if it even works properly.

**Comment by SnazzyPanda** [comment]
I did a bit of searching, and saw some posts on StackOverflow that seems to indicate that the issue could be related to some graphics/driver issue on your end (for example: <https://stackoverflow.com/questions/40644455/x-error-of-failed-request-badvalue-integer-parameter-out-of-range-for-operatio>). I don't think I can really help with that.

**Comment by hardbrocklife** [comment]
I haven't done anything graphically on my PC since attempting to run Lampray, and noticed today with I opened System Monitor that it was throwing an error akin to "currently using software acceleration as hardware is currently unavailable. Please check your GPU drivers".

Ran some updates, none of which were graphics drivers, but now its no longer throwing that error. Linux voodoo.

Thank you for your time regardless. I atleats learned what errors like that are likely to indicate. Closeing the thread.

**Comment by hardbrocklife** [comment]
Error related to graphics drivers.
